/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Codigo.Adn;
import Codigo.Solucion;
import java.util.List;
import javax.swing.JOptionPane;
import Codigo.ArbolBinario;

/**
 * Clase que representa la ventana principal del programa
 * Esta ventana contiene todos los botones para las funcionalidades solicitadas
 * @author edusye
 */
public class Ventana1 extends javax.swing.JFrame {
    private Adn adn;
    private Solucion solucion;
    
    /**
     * Constructor de la clase Ventana1.
     * <p>Inicializa todos los componentes de la interfaz gráfica.</p>
     */
    public Ventana1() {
        initComponents();
        adn = new Adn();
        solucion = new Solucion(adn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        CARGAR = new javax.swing.JButton();
        PATRONES = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();
        FRECUENTE = new javax.swing.JButton();
        NOFRECUENTE = new javax.swing.JButton();
        REPORTE = new javax.swing.JButton();
        LISTA = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setSize(new java.awt.Dimension(700, 600));

        jPanel1.setBackground(new java.awt.Color(223, 242, 242));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        TITULO.setText("BIOINFORMATICA");
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        CARGAR.setBackground(new java.awt.Color(255, 153, 153));
        CARGAR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        CARGAR.setText("CARGAR ARCHIVO");
        CARGAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CARGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARGARMouseClicked(evt);
            }
        });
        jPanel1.add(CARGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 50));

        PATRONES.setBackground(new java.awt.Color(255, 153, 153));
        PATRONES.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        PATRONES.setText("LISTA DE PATRONES");
        PATRONES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PATRONES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PATRONESMouseClicked(evt);
            }
        });
        jPanel1.add(PATRONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, 50));

        BUSCAR.setBackground(new java.awt.Color(255, 153, 153));
        BUSCAR.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        BUSCAR.setText("BUSCAR PATRON");
        BUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUSCARMouseClicked(evt);
            }
        });
        jPanel1.add(BUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 50));

        FRECUENTE.setBackground(new java.awt.Color(255, 153, 153));
        FRECUENTE.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        FRECUENTE.setText("PATRON MAS FRECUENTE");
        FRECUENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(FRECUENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 50));

        NOFRECUENTE.setBackground(new java.awt.Color(255, 153, 153));
        NOFRECUENTE.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        NOFRECUENTE.setText("PATRON MENOS FRECUENTE");
        NOFRECUENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(NOFRECUENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 50));

        REPORTE.setBackground(new java.awt.Color(255, 153, 153));
        REPORTE.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        REPORTE.setText("REPORTE DE COLISIONES");
        REPORTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(REPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, 50));

        LISTA.setBackground(new java.awt.Color(255, 153, 153));
        LISTA.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        LISTA.setText("LISTA TOTAL");
        LISTA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, -1, 50));

        jPanel2.setBackground(new java.awt.Color(223, 242, 242));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de clic del botón CARGAR.
     * Intenta cargar un archivo de ADN y muestra un mensaje informativo del resultado.
     * 
     * @param evt El evento de clic del mouse
     */
    private void CARGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGARMouseClicked
        if (adn.CargarArchivo()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Archivo cargado exitosamente.\nLongitud de la secuencia: " + adn.getLongitudSecuencia(), "Carga Exitosa", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo o la secuencia es inválida.", "Error de Carga", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CARGARMouseClicked

    /**
     * Maneja el evento de clic del botón PATRONES.
     * Valida que haya una secuencia cargada, obtiene los patrones ordenados por frecuencia
     * Abre la ventana de visualización de patrones (Ventana2).
     * 
     * @param evt El evento de clic del mouse
     */
    private void PATRONESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PATRONESMouseClicked
        if (!adn.tieneSecuenciaCargada()) {
            JOptionPane.showMessageDialog(this, "Por favor, carga un archivo de ADN primero.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Validate if the sequence is long enough for at least one triplet
        if (adn.getLongitudSecuencia() < 3) {
            JOptionPane.showMessageDialog(this, "La secuencia de ADN es demasiado corta para formar patrones de 3 caracteres.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<ArbolBinario.Nodo> patronesObtenidos = (List<ArbolBinario.Nodo>) solucion.OrdenadosPorFrecuencia();

        Ventana2 ventana2 = new Ventana2(this);
        ventana2.mostrarPatrones(patronesObtenidos); 
        ventana2.setVisible(true);
        ventana2.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_PATRONESMouseClicked

    /**
     * Maneja el evento de clic del botón BUSCAR.
     * Valida que haya una secuencia cargada, carga los patrones si es necesario
     * Abre la ventana de búsqueda de patrones (Ventana3).
     * 
      * @param evt El evento de clic del mouse
    */
    private void BUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUSCARMouseClicked
        if (!adn.tieneSecuenciaCargada()) {
        JOptionPane.showMessageDialog(this, "Por favor, carga un archivo de ADN primero.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
        }

        // Verificar si hay patrones cargados, si no, cargarlos
        if (!solucion.tienePatronesCargados()) {
            // Cargar los patrones primero
            solucion.OrdenadosPorFrecuencia();
        }

        if (!solucion.tienePatronesCargados()) {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los patrones de ADN.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Ventana3 ventana3 = new Ventana3(this, solucion);
        ventana3.setVisible(true);
        ventana3.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BUSCARMouseClicked

    /**
     * Método principal para ejecutar la aplicación de forma independiente.
     * 
     * Este método configura y crea una instancia de Ventana1 para mostrar la interfaz principal.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CARGAR;
    private javax.swing.JButton FRECUENTE;
    private javax.swing.JButton LISTA;
    private javax.swing.JButton NOFRECUENTE;
    private javax.swing.JButton PATRONES;
    private javax.swing.JButton REPORTE;
    private javax.swing.JLabel TITULO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
