/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Codigo.ArbolBinario;
import java.util.List;

/**
 *
 * @author edusye
 */
public class Ventana2 extends javax.swing.JFrame {
    private Ventana1 ventanaPrincipal;
    
    /**
     * Constructor de Ventana3
     * 
     * @param ventanaPrincipal La instancia de Ventana1 que la invocó
     */
    public Ventana2(Ventana1 ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        if (LISTAPATRON != null) {
            LISTAPATRON.setEditable(false);
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LISTAPATRON = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        VOLVER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LISTAPATRON.setColumns(20);
        LISTAPATRON.setRows(5);
        jScrollPane1.setViewportView(LISTAPATRON);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 600, 510));

        jPanel2.setBackground(new java.awt.Color(223, 242, 242));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 40, 40));

        VOLVER.setBackground(new java.awt.Color(255, 153, 153));
        VOLVER.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        VOLVER.setText("VOLVER");
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });
        jPanel1.add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Vuelve a la ventana principal (Ventana1).
     * 
     * @param evt El evento de clic del mouse que desencadena esta acción.
     */
    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
        this.dispose(); 
        if (ventanaPrincipal != null) {
            ventanaPrincipal.setVisible(true); 
        }
    }//GEN-LAST:event_VOLVERMouseClicked
    
    /**
     * Muestra la lista de patrones en el JTextArea llamado LISTAPATRON.
     * 
     * @param patrones La lista de nodos de patrones a mostrar.
     */
    public void mostrarPatrones(List<ArbolBinario.Nodo> patrones) {
            StringBuilder sb = new StringBuilder();
            if (patrones.isEmpty()) {
                sb.append("No se encontraron patrones o la secuencia no ha sido cargada/procesada correctamente.");
            } else {
                sb.append("Patrones encontrados:\n\n");
                for (ArbolBinario.Nodo nodo : patrones) {
                    sb.append("Patrón: ").append(nodo.patron)
                      .append("\nFrecuencia: ").append(nodo.frecuencia)
                      .append("\nUbicaciones: ").append(nodo.posiciones)
                      .append("\n------------------------------------\n");
                }
            }
            LISTAPATRON.setText(sb.toString());
            LISTAPATRON.setCaretPosition(0);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea LISTAPATRON;
    private javax.swing.JButton VOLVER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
