/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.ArrayList;

/**
 * Ventana para mostrar el reporte de colisiones de la tabla hash.
 * Cuarta ventana del programa.
 * @author edusye
 */
public class Ventana4 extends javax.swing.JFrame {
    private Ventana1 ventanaPrincipal;
    
    /**
     * Constructor de la ventana de reporte.
     * 
     * @param ventanaPrincipal Referencia a la ventana principal.
     */
    public Ventana4(Ventana1 ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        configurarComponentes();
    }
    
    /**
     * Configura los componentes de la interfaz.
     */
    private void configurarComponentes() {
        REPORTE.setEditable(false);
        REPORTE.setLineWrap(true);
    }
    
    /**
     * Muestra el reporte de colisiones en el área de texto.
     * @param reporte Lista de strings con la información del reporte.
     */
    public void mostrarReporte(ArrayList<String> reporte) {
        StringBuilder textoReporte = new StringBuilder();
        
        for (String linea : reporte) {
            textoReporte.append(linea).append("\n");
        }
        
        REPORTE.setText(textoReporte.toString());
        REPORTE.setCaretPosition(0); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        VOLVER = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        REPORTE = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(223, 242, 242));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, -1));

        VOLVER.setBackground(new java.awt.Color(255, 153, 153));
        VOLVER.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        VOLVER.setText("VOLVER");
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });
        jPanel1.add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, 30));

        REPORTE.setColumns(20);
        REPORTE.setRows(5);
        jScrollPane1.setViewportView(REPORTE);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 620, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Maneja el evento de clic del botón VOLVER.
     * Cierra la ventana actual y muestra la ventana principal si está disponible.
     * 
     * @param evt El evento de clic del mouse que desencadena esta acción
     */
    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
        this.dispose();
        if (ventanaPrincipal != null) {
            ventanaPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_VOLVERMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea REPORTE;
    private javax.swing.JButton VOLVER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
